version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::377861569334:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-YTXUGREZOOG0"
permissions_provider = "AWS IAM"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::377861569334:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1J7PWJ4KMB2PS"
cloudformation_execution_role = "arn:aws:iam::377861569334:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-RK5L1UUZ9LWI"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1idm3059hznit"
image_repository = ""
region = "us-east-1"
